import { StyleSheet, Image, Text, View, ImageBackground } from "react-native";
import { CheckBox } from "react-native-elements";
import {Dimensions} from 'react-native';

export default stylesaccountdetails = StyleSheet.create({
    style_Account_Details: {
     position:"relative",
     Width: Dimensions.get("window").width,
     height: 844,
     borderRadius:0,
     backgroundColor: "rgba(255,244,194,1)",
    },
  
    style_profile_icon:{
      position: "absolute",
      width: 35,
      height:35,
      opacity: 1,
      left:330,
      right:"auto",
      top:55,
      bottom:"auto",
  },
  style_favorites_icon:{
      position: "absolute",
      width: 35,
      height:35,
      opacity: 1,
      left:325,
      right:"auto",
      top:785,
      bottom:"auto",
  },
  style_logo:{
      position: "absolute",
      width: 115,
      height: 90,
      opacity: 1,
      left:138,
      right:"auto",
      top:20,
      bottom:"auto",
  },
  style_search_icon:{
      position: "absolute",
      width: 35,
      height:35,
      opacity: 1,
      left: 175,
      right:"auto",
      top: 785,
      bottom:"auto",
  },
  style_homepage_icon:{
      position: "absolute",
      width: 42,
      height: 35,
      opacity: 1,
      left:25,
      right:"auto",
      top:785,
      bottom:"auto",
  },
  style_settings_icon:{
      position: "absolute",
      width: 35,
      height:35,
      opacity: 1,
      left:20,
      right:"auto",
      top:55,
      bottom:"auto",
  },
  style_line:{
    position: "absolute",
    width: 415,
    height: 0,
    borderWidth: 1,
    borderColor: "#CC9966",
    opacity: 0.35,
    right:"auto",
    top: 103,
    bottom:"auto",
    transform: [
        {rotate: "0.28422299948992036deg"},
    ]
},
  style_line_2:{
      position: "absolute",
      width: 415,
      height: 0,
      borderWidth: 1,
      borderColor: "#CC9966",
      opacity: 0.35,
      left: 0,
      right:"auto",
      top: 767,
      bottom:"auto",
  }, 
    style_Edit_Account_Details: {
    position:"absolute",
    width:"auto",
    fontWeight: 400,
    right:40,
    bottom:345,
    textDecorationLine: "none",
    fontSize:26,
    color:"#CC9966",
    //color:"rgba(204,153,102,1)",
    textAlign:"left",
    textAlignVertical:"top",
    letterSpacing:0.1,
    },
    
    buttonSaveChanges:{
      backgroundColor: '#CC9966',
      opacity: 1,
      borderRadius: 20,
      padding: 10,
      left:30,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: 'black',
      borderStyle: 'solid',
      borderWidth: 2,
      //bottom: -660,
      top:590,
      width:330,
      height: 50,
      },
  style_Save_Changes:{
          position: "absolute",
          width: "auto",
          height: "auto",
          right:"auto",
          bottom:"auto",
          color: "#000000",
          letterSpacing: 0.1,
      },
    buttonUpload:{
      backgroundColor: '#CC9966',
      opacity: 1,
      borderRadius: 40,
      padding: 10,
      top:195,
      left:200,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: 'black',
      borderStyle: 'solid',
      borderWidth: 2,
      bottom: -630,
      width:150,
      height: 50,
      },
  style_Upload:{
          position: "absolute",
          width: "auto",
          height: "auto",
          right:"auto",
          bottom:"auto",
          color: "#000000",
          letterSpacing: 0.1,
      },
      inputMail: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 12,
        width: '85%',
        fontSize: 13,
        textAlign: 'left',
        top:170,
      },
      container_1:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      inputName: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 12,
        width: '35%',
        fontSize: 13,
        textAlign: 'left',
        top:125,
        right:100,
      },
      container_2:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      inputSurname: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 12,
        width: '50%',
        fontSize: 13,
        textAlign: 'left',
        top:32,
        left:70,
      },
      container_3:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      inputGenre: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 12,
        width: '35%',
        fontSize: 13,
        textAlign: 'left',
        top:-13,
        right:100,
      },
      container_4:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      inputLocation: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 12,
        width: '50%',
        fontSize: 13,
        textAlign: 'left',
        top:-107,
        left:70,
      },
      container_5:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      inputCountry: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 12,
        width: '85%',
        fontSize: 13,
        textAlign: 'left',
        top:-148,
      },
      container_6:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      inputPassword: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 12,
        width: '85%',
        fontSize: 13,
        textAlign: 'left',
        top:-190,
      },
      container_7:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      inputConfirmPassword: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 12,
        width: '85%',
        fontSize: 13,
        textAlign: 'left',
        top:-232
      },
      container_8:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      style_picture_icon: {
        position:"absolute",
        width: 125,
        height: 85,
        left:30,
        top:175,
        bottom:"auto",
      },
});

  