import { StyleSheet, Image, Text, View, ImageBackground } from "react-native";
import { CheckBox } from "react-native-elements";
import {Dimensions} from 'react-native';

export default stylesaboutcontacts = StyleSheet.create({
    style_OUR_MISSION: {
        position:"absolute",
        width:"auto",
        fontWeight: 400,
        right:53,
        bottom:345,
        textDecorationLine: "none",
        fontSize:28,
        color:"#CC9966",
        textAlign:"center",
        textAlignVertical:"top",
        letterSpacing:0.1,
    },
    style_About: {
        position:"absolute",
        width:"auto",
        fontWeight: 400,
        right:80,
        bottom:275,
        textDecorationLine: "none",
        fontSize:28,
        color:"#CC9966",
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing:0.1,
    },
    style_picture_icon: {
        position:"absolute",
        width: 125,
        height: 85,
        left:130,
        top:305,
        bottom:"auto",
      },
      style_texto_OUR_MISSION: {
        position: "absolute",
        width:170,
        left:"auto",
        fontWeight: 400,
        right:55,
        bottom: 305,
        textDecorationLine: "none",
        fontSize: 10,
        color: "black",
        textAlign: "center",
        textAlignVertical: "center",
        letterSpacing: 0.1,
    },
    style_texto_ABOUT: {
        position:"absolute",
        width:210,
        fontWeight: 400,
        right:40,
        bottom:265,
        textDecorationLine: "none",
        fontSize:10,
        color:"black",
        textAlignVertical:"top",
        letterSpacing:0.1,
    },
    style_line_3:{
        position: "absolute",
        width:415,
        height: 0,
        borderWidth: 1,
        borderColor: "#CC9966",
        opacity: 0.35,
        right:"auto",
        top: 450,
        bottom:"auto",
    },
    style_CONTACTS_US: {
        position:"absolute",
        width:"auto",
        fontWeight: 400,
        right:105,
        bottom:170,
        textDecorationLine: "none",
        fontSize: 25,
        color:"#CC9966",
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing:0.1,
    },
    style_Contact_Mail: {
        position:"absolute",
        width:"auto",
        fontWeight: 400,
        right:40,
        bottom:150,
        textDecorationLine: "none",
        fontSize:10,
        color:"black",
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing:0.1,
    },
    style_FOLLOW_US: {
        position:"absolute",
        width:"auto",
        fontWeight: 400,
        right:120,
        bottom:110,
        textDecorationLine: "none",
        fontSize:25,
        color:"#CC9966",
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing:0.1,
    },
    style_instagram_icon: {
        position:"absolute",
        width: 48,
        height: 48,
        left:30,
        top:658,
        bottom:"auto",
    },
    style_facebook_icon: {
        position:"absolute",
        width: 62,
        height: 62,
        left:115,
        top:650,
        bottom:"auto",
    },
    style_twitter_icon: {
        position:"absolute",
        width: 50,
        height: 50,
        left:220,
        top:656,
        bottom:"auto",
    },
    style_tiktok_icon:{
        position:"absolute",
        width: 50,
        height: 50,
        left:315,
        top:655,
        bottom:"auto",
    },
});