import {StyleSheet, View, Text, Image, Dimensions} from "react-native";
       

export default styles = StyleSheet.create({
  style_Added_Message: {
    top:240,
    right:0,
    backgroundColor: "rgba(1, 1, 1, 0.6)", // Adjust the background color as needed
    color: "white",
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    alignSelf: "center",
  },

  style_Error_Message: {
    top:120,
    right:10,
    backgroundColor: "rgba(1, 1, 1, 0.6)", // Adjust the background color as needed
    color: "white",
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    alignSelf: "center",
  },

  checkboxContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    alignItems: 'center',
  },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 1,
    borderColor: 'black',
    marginRight: 10,
  },
  label: {
    fontSize: 16,
  },
   //Outfit Page
   ViewOutfit:{
    position:"absolute",
    top:10,
    bottom:100
   },
    a: {  
       position: "relative",
       width: 390,
       height: 844,
       overflow:"hidden",
    },
    style_profile_icon:{
        position: "absolute",
        width: 35,
        height:35,
        opacity: 1,
        left:350,
        right:"auto",
        top:60,
        bottom:"auto",
    },
    style_favorites_icon:{
        position: "absolute",
        width: 35,
        height:35,
        opacity: 1,
        left:350,
        right:"auto",
        top:785,
        bottom:"auto",
    },
    style_logo:{
        position: "absolute",
        width: 101,
        height: 92,
        opacity: 1,
        left:145,
        
        right:"auto",
        top:31,
        bottom:"auto",
    },
    style_search_icon:{
        position: "absolute",
        width: 35,
        height:45,
        opacity: 1,
        left: 290,
        right:"auto",
        top: 785,
        bottom:"auto",
    },
    style_homepage_icon:{
        position: "absolute",
        width: 35,
        height: 35,
        opacity: 1,
        left:25,
        right:"auto",
        
        top:798,
        bottom:"auto",
    },
    style_settings_icon:{
        position: "absolute",
        width: 35,
        height:35,
        opacity: 1,
        left:20,
        right:"auto",
        
        top:60,
        bottom:"auto",
    },
    style_Outfit_Details:{
        position: "absolute",
        left: 128,
        top: 145,
        color: "#000000",
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing: 0.1,
    },
    style_line:{
        position: "absolute",
        width: 415,
        height: 0,
        borderWidth: 1,
        borderColor: "#CC9966",
        opacity: 0.35,
        left: 0,
        right:"auto",
        top: 103,
        bottom:"auto",
        transform: [
            {rotate: "0.28422299948992036deg"},
        ]
    },
    style_line_2:{
        position: "absolute",
        width: 415,
        height: 0,
        borderWidth: 1,
        borderColor: "#CC9966",
        opacity: 0.35,
        left: 0,
        right:"auto",
        
        top: 767,
        bottom:"auto",
    },
    style_picture_icon:{
        position: "absolute",
        width: 312,
        height: 229,
        opacity: 1,
        left:45,
        right:"auto",
        top:205,
        bottom:"auto",
    },
    style_Style_:{
        left: 90,
        right:"auto",
        top: 460,
        color: "#000000",
        textAlign:"left",
        letterSpacing: 0.1,
    },
    style_Suited_for_:{
        position: "absolute",
        width: "auto",
        height: "auto",
        left: 45,
        right:"auto",
        top: 250,
        bottom:"auto",
        color: "#000000",
        
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing: 0.1,
    },
    style_line_3:{
        position: "absolute",
        width: 415,
        height: 0,
        borderWidth: 1,
        borderColor: "#CC9966",
        opacity: 0.35,
        left: 0,
        right:"auto",
        top:695,
        bottom:"auto",
        transform: [
            {rotate: "0.4407280654133581deg"},
        ]
    },
    style_About:{
        position: "absolute",
        width: "auto",
        height: "auto",
        left:40,
        right:"auto",
        top: 362,
        bottom:"auto",
        color: "#000000",
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing: 0.1,
    },
    style_Contacts:{
        position: "absolute",
        width: "auto",
        height: "auto",
        left: 140,
        right:"auto",
        top: 362,
        bottom:"auto",
        color: "#000000",
        
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing: 0.1,
    },
    style_Temperature_range_:{
        position: "absolute",
        width: "auto",
        height: "auto",
        left: 45,
        right:"auto",
        top: 270,
        bottom:"auto",
        color: "#000000",
        
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing: 0.1,
    },
    style_Materials_:{
        position: "absolute",
        width: "auto",
        height: "auto",
        left: 45,
        right:"auto",
        top: 290,
        bottom:"auto",
        color: "#000000",
        
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing: 0.1,
    },
    style_Gender_:{
        position: "absolute",
        width: "auto",
        height:"auto",
        left:45,
        right:"auto",
        top:310,
        bottom:"auto",
        color: "#000000",
        
        textAlign: "left",
        textAlignVertical: "top",
        letterSpacing: 0.1,
    },

    //Take Quizz Page
    buttonTakeQuizzPage:{
    backgroundColor: '#CC9966',
    opacity: 0.75,
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: 'black',
    borderStyle: 'solid',
    borderWidth: 2,
    top: -15,
    width:200,
    height: 50,
    },

    style_Take_The_Quizz:{
        position: "absolute",
        width: "auto",
        height: "auto",
        right:"auto",
        bottom:"auto",
        color: "#000000",
        letterSpacing: 0.1,
    },

    //QUIZZ PAGE

    style_Submit:{
        position: "absolute",
        width: "auto",
        height: "auto",
        right:"auto",
        bottom:"auto",
        color: "#000000",
        letterSpacing: 0.1,
    },

    buttonQuizzPage:{
    backgroundColor: '#CC9966',
    opacity: 0.75,
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: 'black',
    borderStyle: 'solid',
    borderWidth: 2,
    bottom: -630,
    width:200,
    height: 50,
    },

    style_Quizz:{
        
        width: "auto",
        height: "auto",
        left: 92,
        right:"auto",
        top: 60,
        bottom:"auto",
        color: "#000000",
        letterSpacing: 0.1,
        textAlignVertical: 'top',
    },

    inputcolours: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 5,
        padding: 10,
        width: '70%',
        fontSize: 12,
        textAlign: 'left',
        top:-50,
    },

    inputstyle: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 5,
        padding: 10,
        width: '70%',
        fontSize: 12,
        textAlign: 'left',
        top:-100,
    },

    inputseasons: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 5,
        padding: 10,
        width: '70%',
        fontSize: 12,
        textAlign: 'left',
        top:-150,
    },

    inputsize: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 5,
        padding: 10,
        width: '70%',
        fontSize: 12,
        textAlign: 'left',
        top:-200,
    },

    style_What_colours:{
        
        width: "auto",
        height: "auto",
        left: 33,
        right:"auto",
        top: 90,
        bottom:"auto",
        color: "#000000",
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing: 0.1,
    },

    style_What_style:{
        position: "absolute",
        width: "auto",
        height: "auto",
        left: 33,
        right:"auto",
        top: 155,
        bottom:"auto",
        color: "#000000",
        
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing: 0.1,
    },

    style_What_seasons:{
        position: "absolute",
        width: "auto",
        height: "auto",
        left: 33,
        right:"auto",
        top: 220,
        bottom:"auto",
        color: "#000000",
        
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing: 0.1,
    },

    style_What_size:{
        position: "absolute",
        width: "auto",
        height: "auto",
        left: 33,
        right:"auto",
        top: 285,
        bottom:"auto",
        color: "#000000",
        
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing: 0.1,
    },

    //PersonalizeOutfitPage




    style_My_Outfit:{
        position: "absolute",
        width: "auto",
        height: "auto",
        left: 88,
        right:"auto",
        top: 55,
        bottom:"auto",
        color: "#000000",
        
        textAlign:"left",
        textAlignVertical:"top",
        letterSpacing: 0.1,
    },

   style_Other_Outfits:{
    position: "absolute",
    width: "auto",
    height: "auto",
    left: 82,
    right:"auto",
    top: 265,
    bottom:"auto",
    color: "#000000",
    textAlign:"left",
    textAlignVertical:"top",
    letterSpacing: 0.1,
   },

   style_picture_icon_1:{
    position: "absolute",
    width: 136,
    height: 130,
    opacity: 1,
    left:276,
    right:"auto",
    top:557,
    bottom:"auto",
},

style_picture_icon_2:{
    position: "absolute",
    width: 136,
    height: 130,
    opacity: 1,
    left:139,
    right:"auto",
    top:557,
    bottom:"auto",
},

style_picture_icon_3:{
    position: "absolute",
    width: 136,
    height: 130,
    opacity: 1,
    left:2,
    right:"auto",
    top:557,
    bottom:"auto",
},

style_line_4:{
    position: "absolute",
    width: 415,
    height: 0,
    borderWidth: 1,
    borderColor: "#CC9966",
    opacity: 0.35,
    left: 0,
    right:"auto",
    
    top: 550,
    bottom:"auto",
},

style_line_5:{
    position: "absolute",
    width: 415,
    height: 0,
    borderWidth: 1,
    borderColor: "#CC9966",
    opacity: 0.35,
    left: 0,
    right:"auto",
    
    top: 690,
    bottom:"auto",
},

style_chapeu:{
    position: "absolute",
    width: 100,
    height: 100,
    opacity: 1,
    left:158,
    right:"auto", 
    top:130,
    bottom:"auto",
},

style_camisola:{
    position: "absolute",
    width: 100,
    height: 100,
    opacity: 1,
    left:158,
    right:"auto",
    top:225,
    bottom:"auto",
},

style_calcas:{
    position: "absolute",
    width: 100,
    height: 100,
    opacity: 1,
    left:158,
    right:"auto",
    top:320,
    bottom:475,
},

style_sapatilhas:{
    position: "absolute",
    width: 100,
    height: 100,
    opacity: 1,
    left:158,
    right:"auto",
    top:420,    
    bottom:370,
    
},

style_play_button_right_1:{
    top:150,
    left: 300,
},
style_play_button_right_2:{
    top:215,
    left: 300,
},
style_play_button_right_3:{
    top:285,
    left: 300,
},
style_play_button_right_4:{
    top:350,
    left: 300,
},

style_play_button_left_1:{
    width:90,
    top:8,
    right: 300,
    left: 0,
    transform: [{ rotate: '-180deg' }], 
},
style_play_button_left_2:{
    top:73,
    left: -300,
    transform: [{ rotate: '-180deg' }],
},
style_play_button_left_3:{
    top:143,
    left: -300,
    transform: [{ rotate: '-180deg' }],
    
},
style_play_button_left_4:{
    top:208,
    left: -300,
    transform: [{ rotate: '-180deg' }],
    
},

//GuestSugestOutfitPage
style_Daily_Outfit:{
  top:100,
  left:150,
  position: "absolute",
  width: "auto",
  height: "auto",
  fontSize: 24,
  color: "rgba(204, 153, 102, 1)",
  textAlign: "left",
  textAlignVertical: "top",
  letterSpacing: 0.1,
},
style_Contacts: {
  position: "absolute",
  width: "auto",
  height: "auto",
  transform: [
    {
      translateX: 135
    },
    {
      translateY: 350
    },
    {
      rotate: "0deg"
    },
  ],fontWeight: 400,
  textDecorationLine: "none",
  fontSize: 24,
  color: "rgba(204, 153, 102, 1)",
  textAlign: "left",
  textAlignVertical: "top",
  letterSpacing: 0.1,
},

//SearchOutfits styles
style_Outfits: {
    position: "absolute",
    width: 200,
    height: "auto",
    transform: [
      {
        translateX: 60
      },
      {
        translateY: 69  //hehe
      },
      {
        rotate: "0deg"
      },
    ],fontWeight: 400,
    textDecorationLine: "none",
    fontSize: 24,
    color: "rgba(204, 153, 102, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  style_Contacts: {
    position: "absolute",
    width: "auto",
    height: "auto",
    transform: [
      {
        translateX: 0
      },
      {
        translateY: 0
      },
      {
        rotate: "0deg"
      },
    ],fontWeight: 400,
    textDecorationLine: "none",
    fontSize: 24,
    color: "rgba(204, 153, 102, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  style_About: {
    position: "absolute",
    width: "auto",
    height: "auto",
    transform: [
      {
        translateX: 10
      },
      {
        translateY: 350
      },
      {
        rotate: "0deg"
      },
    ],fontWeight: 400,
    textDecorationLine: "none",
    fontSize: 24,
    color: "rgba(204, 153, 102, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  style_Contacts: {
    position: "absolute",
    width: "auto",
    height: "auto",
    transform: [
      {
        translateX: 135
      },
      {
        translateY: 350
      },
      {
        rotate: "0deg"
      },
    ],fontWeight: 400,
    textDecorationLine: "none",
    fontSize: 24,
    color: "rgba(204, 153, 102, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  style_Search: {
    position: "absolute",
    width: "auto",
    height: "auto",
    fontWeight: 400,
    textDecorationLine: "none",
    fontSize: 24,
    color: "rgba(204, 153, 102, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },  
  style_pictureicon: {
    position: "absolute",
    width: 105,
    height: 104,
    borderRadius: 0,
    opacity: 1,
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: "0deg" }
    ],
    backgroundColor: "rgba(0,0,0,0)",
  },
  //password reset styles
  style_Password_reset: {
    position: "relative",
    width: 238,
    height: 75,
    transform: [
      { translateX: 60 },
      { translateY: -5 },
      { rotate: "0deg" },
    ],
  
    fontWeight: 400,
    textDecorationLine: "none",
    fontSize: 24,
    color: "rgba(204, 153, 102, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  style_Send_Email: {
    position: "absolute",
    top: 7 ,
    left: 80 ,
    width: 286,
    height: 209,
    textDecorationLine: "none",
    fontSize: 20,
    color: "rgba(42, 42, 42, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  //all the icons styles
  style_profile_icon:{
    position: "absolute",
    width: 35,
    height:35,
    opacity: 1,
    left:350,
    right:"auto",
    top:60,
    bottom:"auto",
},
1:{
    position: "absolute",
    width: 35,
    height:35,
    opacity: 1,
    left:350,
    right:"auto",
    top:790,
    bottom:"auto",
},
style_logo:{
    position: "absolute",
    width: 101,
    height: 92,
    opacity: 1,
    left:145,

    right:"auto",
    top:31,
    bottom:"auto",
},
style_search_icon:{
    position: "absolute",
    width: 35,
    height:35,
    opacity: 1,
    left: 190,
    right:"auto",
    top: 785,
    bottom:"auto",
},
style_homepage_icon:{
    position: "absolute",
    width: 35,
    height: 35,
    opacity: 1,
    left:25,
    right:"auto",
    top:785,
    bottom:"auto",
},
style_settings_icon:{
    position: "absolute",
    width: 35,
    height:35,
    opacity: 1,
    left:10,
    right:"auto",

    top:60,
    bottom:"auto",
},
style_line:{
    position: "absolute",
    width: 415,
    height: 0,
    borderWidth: 2,
    borderColor: "#CC9966",
    opacity: 0.45,
    left: 1,
    right:"auto",
    top: 303,
    bottom:"auto",
    transform: [
        {rotate: "0.28422299948992036deg"},
    ]
},
style_line_2_unused:{
    position: "absolute",
    width: 415,
    height: 0,
    borderWidth: 1,
    borderColor: "#CC9966",
    opacity: 0.35,
    left: 1,
    right:10,
    top: 767,
    bottom:"auto",
},

  style_Background: {
    position: 'relative',
    width: 1000,
    height: 1000,
    borderRadius: 0,
    backgroundColor: 'rgba(255, 244, 194, 1)',
  },
  style_profileicon: {
    position: 'absolute',
    width: 35,
    height: 35,
    borderRadius: 0,
    opacity: 1,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 1)',
    left: 318,
    right: 'auto',
    top: 60,
    bottom: 'auto',
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: '0deg' },
    ],
    backgroundColor: 'rgba(0, 0, 0, 0)',
  },
  style_favoritesicon: {
    position: 'absolute',
    width: 35,
    height: 35,
    borderRadius: 0,
    opacity: 1,
    left: 318,
    right: 'auto',
    top: 798,
    bottom: 'auto',
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: '0deg' },
    ],
    backgroundColor: 'rgba(0, 0, 0, 0)',
  },
  style_logo: {
    position: 'absolute',
    width: 101,
    height: 92,
    borderRadius: 0,
    opacity: 1,
    left: 145,
    right: 'auto',
    top: 31,
    bottom: 'auto',
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: '0deg' },
    ],
    backgroundColor: 'rgba(0, 0, 0, 0)',
  },
  style_searchicon: {
    position: 'absolute',
    width: 35,
    height: 35,
    borderRadius: 0,
    opacity: 1,
    left: 173,
    right: 'auto',
    top: 798,
    bottom: 'auto',
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: '0deg' },
    ],
    backgroundColor: 'rgba(0, 0, 0, 0)',
  },
  style_homepageicon: {
    position: 'absolute',
    width: 35,
    height: 35,
    borderRadius: 0,
    opacity: 1,
    left: 28,
    right: 'auto',
    top: 798,
    bottom: 'auto',
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: '0deg' },
    ],
    backgroundColor: 'rgba(0, 0, 0, 0)',
  },
  style_settingsicon: {
    position: "absolute",
    width: 35,
    height: 35,
    borderRadius: 0,
    opacity: 1,
    left: 24,
    right: "auto",
    top: 60,
    bottom: "auto",
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: "0deg" },
    ],
    backgroundColor: "rgba(0,0,0,0)",
  },
  style_Line_1: {
    position: "absolute",
    width: 500,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(204, 153, 102, 1)",
    left: 0,
    top: 103,
  },
  style_Line_2: {
    width: 500,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(204, 153, 102, 1)",
    right:10,
    top: 767,
    transform: [
      { translateX: 10 },
      { translateY: 0 },
      { rotate: "0deg" },
    ],
  },
  style_Line_3: {
    position: "absolute",
    width: 390,
    height: 0,
    borderRadius: 0,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(204, 153, 102, 1)",
    left: 0,
    right: "auto",
    top: 767,
    bottom: "auto",
    transform: [
      { translateX: 0 },
      { translateY: 100 },
      { rotate: "0deg" },
    ],
  },
  style_Line_4: {
    position: "absolute",
    width: 390,
    height: 0,
    borderRadius: 0,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(204, 153, 102, 1)",
    left: 0,
    right: "auto",
    top: 767,
    bottom: "auto",
    transform: [
      { translateX: 10 },
      { translateY: 0 },
      { rotate: "0deg" },
    ],
  },
  style_Group_16: {
    position: "absolute",
    top:270,
    left:50,
    width: 300,
    height: 800,
    overflow: "hidden",
    backgroundColor: "rgba(0,0,0,0)",
  },
  //styles para o LoggInPage
  style_Group_16_1: {
    position:"relative",
    marginTop: 10, // Adjust the top margin value as needed
    width: 400, // Adjust the width as needed
    height: 200, // Adjust the height as needed
    backgroundColor: 'rgba(0, 0, 0, 0)',
  },
  style_Log_In: {
    position: "absolute",
    width: 279,
    height: 33,
    left: 120,
    right: 10,
    top: 170,
    bottom: 0,
    fontWeight: 400,
    fontSize: 24,
    color: "rgba(204, 153, 102, 1)",
    letterSpacing: 0.1,
  },
  style_Group_14: {
    position: "absolute",
    width: 286.19403076171875,
    height: 196.53976440429688,
    transform: [
      { translateX: 0 },
      { translateY: 65 },
      { rotate: "0deg" },
    ],
    overflow: "hidden",
    backgroundColor: "rgba(0,0,0,0)",
  },
  style_Rectangle_33: {
    position: "absolute",
    width: 286.19403076171875,
    height: 44.29823303222656,
    borderRadius: 20,
    opacity: 1,
    borderWidth: 1,
    borderColor: "rgba(196, 196, 196, 1)",
    left: 0,
    right: "auto",
    top: 70,
    bottom: "auto",
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: "0deg" }
    ],
    backgroundColor: "rgba(255, 255, 255, 1)"
  },
  style_Rectangle_33_1: {
    position: "absolute",
    width: 286.19403076171875,
    height: 44.29823303222656,
    borderRadius: 20,
    opacity: 1,
    borderWidth: 1,
    borderColor: "rgba(196, 196, 196, 1)",
    left: 0,
    right: "auto",
    top: 2,
    bottom: "auto",
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: "0deg" }
    ],
    backgroundColor: "rgba(255, 255, 255, 1)"
  },
  style_Email: {
    position: "absolute",
    width: 200,
    height: 30,
    left: 20,
    right: 10,
    top: 5,
    bottom: 10,
    fontSize: 14,
    color: "rgba(196, 196, 196, 1)",
    letterSpacing: 0.1
  },
  style_Email_1: {
    position: "absolute",
    width: 240,
    height: 18,
    left: 10,
    right: "auto",
    top: 5,
    bottom: "auto",
    textDecorationLine: "none",
    fontSize: 14,
    color: "rgba(196, 196, 196, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1
  },
  
  style_Rectangle_34: {
    position: "absolute",
    width: 286.19403076171875,
    height: 44.29823303222656,
    borderRadius: 20,
    opacity: 1,
    borderWidth: 1,
    borderColor: "rgba(196, 196, 196, 1)",
    left: 0,
    right: "auto",
    top: 72,
    bottom: "auto",
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: "0deg" }
    ],
    backgroundColor: "rgba(255, 255, 255, 1)"
  },
  style_Password: {
    width: 240,
    height: 17,
    left: 17,
    top: 13,
    fontSize: 14,
    color: "rgba(196, 196, 196, 1)",
    letterSpacing: 0.1
  },
  style_Rectangle_35_1: {
    position: "absolute",
    width: 286,
    height: 52,
    borderRadius: 20,
    opacity: 1,
    borderWidth: 2,
    borderColor: "rgba(42, 42, 42, 1)",
    left: 0,
    right: "auto",
    top: 174,
    bottom: "auto",
    backgroundColor: "rgba(204, 153, 102, 1)",
  }, 
  style_Rectangle_35_2: {
    position: "absolute",
    width: 286.19403076171875,
    height: 52.539764404296875,
    borderRadius: 20,
    opacity: 1,
    borderWidth: 2,
    borderColor: "rgba(42, 42, 42, 1)",
    left: 46.5,
    right: "auto",
    top: 504,
    bottom: "auto",
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: "0deg" },
    ],
    backgroundColor: "rgba(204, 153, 102, 1)",
  }, 
  
  style_Log_In_1: {
    position: "absolute",
    width: 100,
    height: 33,
    left: 95,
    right: "auto",
    top: 8,
    bottom: "auto",
    fontWeight: 400,
    textDecorationLine: "none",
    fontSize: 24,
    color: "rgba(42, 42, 42, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  //other page 
  style_Rectangle_36: {
    position: "absolute",
    width: 286.19403076171875,
    height: 52.539764404296875,
    borderRadius: 20,
    opacity: 1,
    borderWidth: 2,
    borderColor: "rgba(42, 42, 42, 1)",
    left: 0,
    right: "auto",
    top: 144,
    bottom: "auto",
    transform: [
      { translateX: 60 },
      { translateY: 400 },
      { rotate: "0deg" },
    ],
    backgroundColor: "rgba(204, 153, 102, 1)",
  },

   style_Rectangle_35: {
    position: "absolute",
    width: 286.19403076171875,
    height: 52.539764404296875,
    borderRadius: 20,
    opacity: 1,
    borderWidth: 2,
    borderColor: "rgba(42, 42, 42, 1)",
    left: 0,
    right: "auto",
    top: 144,
    bottom: "auto",
    transform: [
      { translateX: 60 },
      { translateY: 200 },
      { rotate: "0deg" },
    ],
    backgroundColor: "rgba(204, 153, 102, 1)",
  },
  style_Rectangle_35_3: {
    position: "absolute",
    width: 286.19403076171875,
    height: 52.539764404296875,
    borderRadius: 20,
    opacity: 1,
    borderWidth: 2,
    borderColor: "rgba(42, 42, 42, 1)",
    left: 60,
    right: "auto",
    top: 650,
    bottom: "auto",
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: "0deg" },
    ],
    backgroundColor: "rgba(204, 153, 102, 1)",
  },
  style_Rectangle_35_4: {
    position: "absolute",
    width: 286.19403076171875,
    height: 52.539764404296875,
    borderRadius: 20,
    opacity: 1,
    borderWidth: 2,
    borderColor: "rgba(42, 42, 42, 1)",
    left: 60,
    right: "auto",
    top: 550,
    bottom: "auto",
    backgroundColor: "rgba(204, 153, 102, 1)",
  },
  style_Forgot_Password_: {
    width: 200,
    height: 30,
    left: 20,
    top: 40,
    lineHeight: 24,
    fontSize: 16,
    color: "rgba(33, 37, 41, 1)",
    letterSpacing: 0.1,
  },
  style_div_form_group: {
    position: "absolute",
    width: 255,
    height: 68,
    left: 106,
    right: "auto",
    top: 560,
    bottom: "auto",
  },
  style_input_terms: {
    position: "absolute",
    width: 13,
    height: 13,
    borderRadius: 2.5,
    opacity: 1,
    borderWidth: 1,
    borderColor: "rgba(118, 118, 118, 1)",
    left: 0,
    right: "auto",
    top: 16,
    bottom: "auto",
    transform: [
      { translateX: 0 },
      { translateY: 0 },
      { rotate: "0deg" },
    ],
    backgroundColor: "rgba(255, 255, 255, 1)",
  },
  //loggin page
  style_Keep_me_logged_in: {
    position: "absolute",
    width: 243.8718719482422,
    height: 46,
    left: 20,
    right: "auto",
    top: 0,
    bottom: "auto",
    textDecorationLine: "none",
    lineHeight: 24,
    fontSize: 16,
    color: "rgba(33, 37, 41, 1)",
    textAlign: "left",
    textAlignVertical: "center",
    letterSpacing: 0.1,
  },
  //logg in or register

  style_OR: {
    top:450,
    left:175,
    width: 35,
    height: 33,
    fontSize: 24,
    color: "rgba(204, 153, 102, 1)",
    letterSpacing: 0.1,
    },
  style_LOG_IN: {
    left: 105,
    top: 6,
    bottom: 10,
    fontSize: 20,
    color: "rgba(42, 42, 42, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
   style_DELETE: {
    position: "absolute",
    width: 200,
    height: 50,
    left: 50,
    right: "auto",
    top: 5,
    bottom: "auto",
    textDecorationLine: "none",
    fontSize: 20,
    color: "rgba(42, 42, 42, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  style_ADD: {
    position: "absolute",
    width: 200,
    height: 50,
    left: 60,
    right: "auto",
    top: 5,
    bottom: "auto",
    textDecorationLine: "none",
    fontSize: 20,
    color: "rgba(42, 42, 42, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  style_REGISTRAR: {
    position: "absolute",
    width: "auto",
    height: "auto",
    left: 90,
    right: "auto",
    top: 8,
    bottom: "auto",
    textDecorationLine: "none",
    fontSize: 20,
    color: "rgba(42, 42, 42, 1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  
  style_AddToFavorites: {
    position: "absolute",
    width: "auto",
    height: "auto",
    left: 10,
    right: "auto",
    top: 11,
    bottom: "auto",
    textDecorationLine: "none",
    fontSize: 16,
    color: "rgba(42, 42, 42, 1)",
    textAlign: "center",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  style_Quizz_Button: {
    position: "absolute",
    width: 126,
    height: 72,
    borderRadius: 20,
    opacity: 1,
    borderWidth: 2,
    borderColor: "rgba(42, 42, 42, 1)",
    left: 28,
    right: "auto",
    top: 585,
    bottom: "auto",
    backgroundColor: "rgba(204, 153, 102, 1)",
  },
  style_Rectangle_36_User: {
    position: "absolute",
    width: 126,
    height: 72,
    borderRadius: 20,
    opacity: 1,
    borderWidth: 2,
    borderColor: "rgba(42, 42, 42, 1)",
    left: 240,
    right: "auto",
    top: 585,
    bottom: "auto",
    backgroundColor: "rgba(204, 153, 102, 1)",
  },
  style_QuizzText: {
    position: "absolute",
    width: "auto",
    height: "auto",
    left: 10,
    right: "auto",
    top: 11,
    bottom: "auto",
    textDecorationLine: "none",
    fontSize: 16,
    color: "rgba(42, 42, 42, 1)",
    textAlign: "center",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },



//favourites buttons

style_play_button_left_1_favourites:{
  width:90,
  top:520,
  right: 300,
  left: 0,
  transform: [{ rotate: '180deg' }], 
},
style_play_button_right_1_favourites:{
  top: 555,
  left: 300,
},
style_Rectangle_36_favourites: {
  position: "absolute",
  width: 126,
  height: 72,
  borderRadius: 20,
  opacity: 1,
  borderWidth: 2,
  borderColor: "rgba(42, 42, 42, 1)",
  left: 130,
  right: "auto",
  top: 555,
  bottom: "auto",
  backgroundColor: "rgba(204, 153, 102, 1)",
  
},

style_favourites_image:{
left:-15,
},
 
});









    
    










