import { StyleSheet, Image, Text, View, ImageBackground } from "react-native";
import { CheckBox } from "react-native-elements";
import {Dimensions} from 'react-native';


export default stylesfavorites = StyleSheet.create({
style_Favorites: {
    position:"absolute",
    //width:"auto",
    fontWeight: 400,
    right:68,
    bottom:345,
    textDecorationLine: "none",
    fontSize:30,
    color:"#CC9966",
    textAlign:"center",
    textAlignVertical:"top",
    letterSpacing:0.1,
},
style_Texto_1: {
    position: "absolute",
    fontWeight: 400,
    right: 125,
    bottom: 330,
    textDecorationLine: "none",
    fontSize: 13,
    color: "black",
    textAlign: "center",
    textAlignVertical: "center",
    letterSpacing: 0.1,
  },
  style_line_3:{//linha spring
    position: "absolute",
    width: 415,
    height: 0,
    borderWidth: 1,
    borderColor: "#CC9966",
    opacity: 0.35,
    right:"auto",
    top: 185,
    bottom:"auto",
},
  style_picture_icon: {
    position:"absolute",
    width: 125,
    height: 85,
    left:5,
    top:200,
    bottom:"auto",
  },
  style_picture_icon_1: {
    position:"absolute",
    width: 125,
    height: 85,
    left:132,
    top:200,
    bottom:"auto",
  },
  style_picture_icon_2: {
    position:"absolute",
    width: 125,
    height: 85,
    left:260,
    top:200,
    bottom:"auto",
  },
  style_Texto_2: {
    position: "absolute",
    fontWeight: 400,
    right: 120,
    bottom: 260,
    textDecorationLine: "none",
    fontSize: 13,
    color: "black",
    textAlign: "center",
    textAlignVertical: "center",
    letterSpacing: 0.1,
  },
  style_line_4:{//linha summer
    position: "absolute",
    width: 415,
    height: 0,
    borderWidth: 1,
    borderColor: "#CC9966",
    opacity: 0.35,
    right:"auto",
    top: 300,
    bottom:"auto",
},
style_picture_icon_3: {
    position:"absolute",
    width: 125,
    height: 85,
    left:260,
    top:335,
    bottom:"auto",
  },
  style_picture_icon_4: {
    position:"absolute",
    width: 125,
    height: 85,
    left:5,
    top:335,
    bottom:"auto",
  },
  style_picture_icon_5: {
    position:"absolute",
    width: 125,
    height: 85,
    left:132,
    top:335,
    bottom:"auto",
  },
  style_line_5:{//linha fall
    position: "absolute",
    width: 415,
    height: 0,
    borderWidth: 1,
    borderColor: "#CC9966",
    opacity: 0.35,
    right:"auto",
    top: 435,
    bottom:"auto",
},
  style_Texto_3: {
    position: "absolute",
    fontWeight: 400,
    right: 135,
    bottom:192,
    textDecorationLine: "none",
    fontSize: 13,
    color: "black",
    textAlign: "center",
    textAlignVertical: "center",
    letterSpacing: 0.1,
  },
  style_picture_icon_6: {
    position:"absolute",
    width: 125,
    height: 85,
    left:5,
    top:475,
    bottom:"auto",
  },
style_picture_icon_7: {
    position:"absolute",
    width: 125,
    height: 85,
    left:132,
    top:475,
    bottom:"auto",
  },
  style_picture_icon_8: {
    position:"absolute",
    width: 125,
    height: 85,
    left:260,
    top:475,
    bottom:"auto",
  },
  style_line_6:{//linha winter
    position: "absolute",
    width: 415,
    height: 0,
    borderWidth: 1,
    borderColor: "#CC9966",
    opacity: 0.35,
    right:"auto",
    top: 575,
    bottom:"auto",
},
  style_Texto_4: {
    position: "absolute",
    fontWeight: 400,
    right: 125,
    bottom: 122,
    textDecorationLine: "none",
    fontSize: 13,
    color: "black",
    textAlign: "center",
    textAlignVertical: "center",
    letterSpacing: 0.1,
  },
  style_picture_icon_9: {
    position:"absolute",
    width: 125,
    height: 85,
    left:5,
    top:610,
    bottom:"auto",
  },
  style_picture_icon_10: {
    position:"absolute",
    width: 125,
    height: 85,
    left:132,
    top:610,
    bottom:"auto",
  },
  style_picture_icon_11: {
    position:"absolute",
    width: 125,
    height: 85,
    left:260,
    top:610,
    bottom:"auto",
  },  
style_About: {
    position:"absolute",
    width:"auto",
    fontWeight: 400,
    right:135,
    bottom:45,
    textDecorationLine: "none",
    fontSize:25,
    color:"#CC9966",
    textAlign:"left",
    textAlignVertical:"top",
    letterSpacing:0.1,
},
style_Contacts: {
    position:"absolute",
    width:"auto",
    fontWeight: 400,
    right:35,
    bottom:45,
    textDecorationLine: "none",
    fontSize:25,
    color:"#CC9966",
    textAlign:"left",
    textAlignVertical:"top",
    letterSpacing:0.1,
},





});