import { StyleSheet, Image, Text, View, ImageBackground } from "react-native";
import { CheckBox } from "react-native-elements";
import {Dimensions} from 'react-native';


export default stylesclothesdetails = StyleSheet.create({
    style_Clothes_Details: {
        position:"absolute",
        //width:"auto",
        fontWeight: 400,
        right:52,
        bottom:335,
        textDecorationLine: "none",
        fontSize:30,
        color:"#CC9966",
        textAlign:"center",
        textAlignVertical:"top",
        letterSpacing:0.1,
    },
    inputColor: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 13,
        width: '85%',
        fontSize: 14,
        textAlign: 'left',
        top:168,
      },
      container_1:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      inputMaterial: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 14,
        width: '85%',
        fontSize: 13,
        textAlign: 'left',
        top:105,
      },
      container_2:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      inputPart_of_the_Body: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 14,
        width: '85%',
        fontSize: 13,
        textAlign: 'left',
        top:40,
      },
      container_3:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      inputInterval_of_Temperature: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 14,
        width: '85%',
        fontSize: 13,
        textAlign: 'left',
        top:-25,
      },
      container_4:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      inputClimatic_Conditions: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 14,
        width: '85%',
        fontSize: 13,
        textAlign: 'left',
        top:-90,
      },
      container_5:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      inputGenre: {
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor:"white",
        borderRadius: 50,
        padding: 14,
        width: '85%',
        fontSize: 13,
        textAlign: 'left',
        top:-155,
      },
      container_6:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
    buttonUploadPicture:{
        backgroundColor: 'white',
        opacity: 1,
        borderRadius: 20,
        padding: 15,
        top:500,
        left:28,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: '#ddd',
        borderStyle: 'solid',
        borderWidth: 1,
        //bottom:50,
        width:150,
        height: 50,
        },
    style_Upload_Picture:{
            position: "absolute",
            width: "auto",
            height: "auto",
            right:"auto",
            bottom:"auto",
            color: "#ddd",
            letterSpacing: 0.1,
        },
    buttonSave:{
        backgroundColor: '#CC9966',
        opacity: 1,
        borderRadius: 20,
        padding: 10,
        left:30,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'black',
        borderStyle: 'solid',
        borderWidth: 2,
        bottom:0,
        top:10,
        width:330,
        height: 50,
        },
    style_Save:{
            position: "absolute",
            width: "auto",
            height: "auto",
            right:"auto",
            bottom:"auto",
            color: "black",
            letterSpacing: 0.1,
        },


});