import { StyleSheet, Image, Text, View, ImageBackground } from "react-native";
import { CheckBox } from "react-native-elements";
import {Dimensions} from 'react-native';

export default stylesLogOutorAcc = StyleSheet.create({
  style_logo:{
    position: "absolute",
    width: 115,
    height: 92,
    opacity: 1,
    left:135,
    right:"auto",
    top:20,
    bottom:"auto",
},
style_line:{
    position: "absolute",
    width: 415,
    height: 0,
    borderWidth: 1,
    borderColor: "#CC9966",
    opacity: 0.35,
    right:"auto",
    top: 103,
    bottom:"auto",
   
},
style_line_2:{
    position: "absolute",
    width: 415,
    height: 0,
    borderWidth: 1,
    borderColor: "#CC9966",
    opacity: 0.35,
    right:"auto",
    top: 767,
    bottom:"auto",
},
buttonLogOut:{
  backgroundColor: '#CC9966',
  opacity: 1,
  borderRadius: 20,
  padding: 10,
  alignItems: 'center',
  justifyContent: 'center',
  borderColor: 'black',
  borderStyle: 'solid',
  borderWidth: 2,
  bottom: -305,
  left:55,
  width:280,
  height: 50,
  },
style_Log_Out:{
      right:5,
      fontSize:16,
      color: "#000000",
      letterSpacing: 0.1,
  },
  style_Or: {
      position:"absolute",
      width:"auto",
      fontWeight: 400,
      right:90,
      bottom:205,
      textDecorationLine: "none",
      fontSize:30,
      color:"#CC9966",
      textAlign:"left",
      textAlignVertical:"top",
      letterSpacing:0.1,  
    },
    buttonAccountDetails:{
      backgroundColor: '#CC9966',
      opacity: 1,
      borderRadius: 20,
      padding: 10,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: 'black',
      borderStyle: 'solid',
      borderWidth: 2,
      left:55,
      bottom: -425,
      width:280,
      height: 50,
      },
      style_Account_Details:{
        position: "absolute",
        width: "auto",
        height: "auto",
        right:"auto",
        bottom:"auto",
        fontSize:16,
        color: "#000000",
        letterSpacing: 0.1,
    },
    style_homepage_icon:{
      position: "absolute",
      width: 35,
      height: 35,
      opacity: 1,
      left:25,
      right:"auto",
      top:55,
      bottom:"auto",
  },
  });

  